computeMethod   ::= callMethod ( ( ':' targetAttributeName ) |  )

callMethod      ::= ( staticClass |  ) '::' methodName '(' ( methodInputs |  ) ')'

methodInputs    ::= methodInput ( ',' methodInput )*

methodInput     ::= '<spaces>'* ( sourceAttributeName | text | keyWord ) '<spaces>'*

text            ::= ( "'" '<text>' ) | ( "'" "[^',]+" "'" ) | ( '"' '[^",]+' '"' )

keyWord         ::= 'THIS' | 'K'