inputHelp       ::= funcName '(' ( funcInputs |  ) ')' ':' funcOutputs

funcInputs      ::= funcInput ( ',' funcInput )*

funcInput       ::= ( sourceAttributeName | familyParameterName | text | sourceKeyWord | propertyName | '{' appParameterName '}' | '{' familyName '}' )

funcOutputs     ::= funcOutput ( ',' funcOutput )*

funcOutput      ::= ( targetAttributeName | targetKeyWord )

text            ::= ( "'" '<text>' ) | ( "'" "[^',]+" "'" ) | ( '"' '[^",]+' '"' )

sourceKeyWord   ::= ( 'CT' | 'CT' '[' relationAttributeName ']' | 'D' | 'I' | 'K' | 'T' | 'A' )

targetKeyWord   ::= ( 'CT' | 'CT' '[' relationAttributeName ']' )